name: build-pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  repo: sr79979
  image_name1: youtube-clone
  image_name2: band-booking
  build_number: ${{ github.run_number }}
  PROJECTS: "project1 project2"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_projects: ${{ steps.set-changed-projects.outputs.changed_projects }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is available
      
      - name: Debug - Show Git Diff
        run: |
          echo "Checking changes between ${{ github.event.before }} and ${{ github.sha }}"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      
      - name: Detect Changes in Projects
        id: set-changed-projects
        run: |
          CHANGED_PROJECTS=""
          for project in $PROJECTS; do
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^$project/"; then
              CHANGED_PROJECTS+="$project "
            fi
          done
          echo "Changed Projects: $CHANGED_PROJECTS"
          echo "changed_projects=$CHANGED_PROJECTS" >> $GITHUB_OUTPUT

  build:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_projects != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          set -x
          CHANGED_PROJECTS="${{ needs.detect-changes.outputs.changed_projects }}"
          echo "changed_projects=$CHANGED_PROJECTS" >> $GITHUB_ENV
          for project in $CHANGED_PROJECTS; do
            echo "🔹 Processing $project"
            if [ "$project" == "project2" ]; then
              echo "🔧 Running Maven Build for $project"
              cd $project
              mvn clean package
              cd ..
            fi
            cd $project
            echo "🐳 Building Docker Image for $project"
            docker build . --file Dockerfile --tag $project:${{ env.build_number }}
            cd ..
            echo "Converting the image into Tar file"
            docker save $project:${{ env.build_number }} -o $project.tar
            ls -lart
          done
                  
          echo "Changed Projects: $CHANGED_PROJECTS"
          echo "changed_projects=$CHANGED_PROJECTS" >> $GITHUB_OUTPUT

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: "*.tar"
      - name: Check files
        run: |
          ls -lart
          docker images

  scan:
    needs: [detect-changes, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .
      - name: Install Trivy Scanner
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.59.1/trivy_0.59.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.59.1_Linux-64bit.deb
      
      - name: Debug show detected changed projects
        run: |
          echo "Received changed projects: ${{ needs.detect-changes.outputs.changed_projects }}"
      - name: Scan Docker Image for Vulnerabilities
        id: scan-results
        run: |
          set -x
          echo "detect:${{ needs.detect-changes.outputs.changed_projects }}"
          CHANGED_PROJECTS="${{ needs.detect-changes.outputs.changed_projects }}"
          echo "changed_projects=$CHANGED_PROJECTS" >> $GITHUB_ENV
          if [ -z "$CHANGED_PROJECTS" ]; then
            echo "No Changed projects detected."
            exit 0
          fi
          SCAN_RESULTS=""
          for project in $CHANGED_PROJECTS; do
            echo "🛡️ Scanning $project"
            trivy image --format table --input $project.tar --output scan_${project}.md || true
            grep -E 'Total:|HIGH:|CRITICAL:' scan_${project}.md > scan_summary_${project}.md || echo "No vulnerabilities found!" > scan_summary_${project}.md
            HIGH_COUNT=$(grep -oP 'HIGH:\s+\K\d+' scan_summary_${project}.md | awk '{sum+=$1} END {print sum+0}')
            CRITICAL_COUNT=$(grep -oP 'CRITICAL:\s+\K\d+' scan_summary_${project}.md | awk '{sum+=$1} END {print sum+0}')
            if [ "$HIGH_COUNT" -gt 0 ] || [ "$CRITICAL_COUNT" -gt 0 ]; then
              SCAN_RESULTS+="$project: ❌ High or Critical vulnerabilities found.\n"
              grep -E 'Total:|HIGH:|CRITICAL:' scan_${project}.md
            else
              SCAN_RESULTS+="$project: ✅ No high or critical vulnerabilities.\n"
            fi
            ls -lart
          done
          cat 
          ls -lart
          echo "SCAN_RESULTS=$SCAN_RESULTS" >> $GITHUB_ENV
          echo "scan_results=$SCAN_RESULTS" >> $GITHUB_OUTPUT
      - name: Upload Scan Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-scan
          path: "scan_*.md"

  push:
    needs: [detect-changes, scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .
      - name: Load Docker Image
        run: |
          CHANGED_PROJECTS="${{ needs.detect-changes.outputs.changed_projects }}"
          for project in $CHANGED_PROJECTS; do
            docker load -i $project.tar
            docker images
          done
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Tag and Push Docker Image
        run: |
          CHANGED_PROJECTS="${{ needs.detect-changes.outputs.changed_projects }}"
          echo "scan_reports:${{ needs.scan.outputs.scan_results }}"
          for project in $CHANGED_PROJECTS; do
            if echo "${{ needs.scan.outputs.scan_results }}" | grep -q "$project: ❌"; then
              echo "⏩ Skipping push for $project due to vulnerabilities."
              continue
            fi
            docker tag $project:${{ env.build_number }} ${{ env.repo }}/$project:${{ env.build_number }}
            docker push ${{ env.repo }}/$project:${{ env.build_number }}
           done
      - name: Update README with Image Path & Scan Report
        run: |
          CHANGED_PROJECTS="${{ needs.detect-changes.outputs.changed_projects }}"
          echo "scan_reports:${{ needs.scan.outputs.scan_results }}"
          for project in $CHANGED_PROJECTS; do
            echo "## $project Latest Docker Images" >> README.md
            echo "Image: \`${{ env.repo }}/$project:${{ env.build_number }}\`" >> README.md
            echo "## $project Vulnerability Scan Report" >> README.md
            cat scan_summary_${project}.md >> README.md
          done
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with Docker Image & Scan Report" || echo "No changes to the commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
